# This workflow builds publish DocC docs to GitHub Pages.
# Source: https://maxxfrazer.medium.com/deploying-docc-with-github-actions-218c5ca6cad5
# Sample: https://github.com/AgoraIO-Community/VideoUIKit-iOS/blob/main/.github/workflows/deploy_docs.yml

name: DocC Runner

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - id: pages
        uses: actions/configure-pages@v5

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4.0'

      - name: Build DocC
        working-directory: ./CordovaLib
        run: |
          swift package resolve;
          
          xcodebuild docbuild -scheme Cordova -derivedDataPath /tmp/docbuild -destination 'generic/platform=iOS';
          
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/Cordova.doccarchive \
            --output-path docs \
            --hosting-base-path 'cordova-ios-docs';
            
          echo "<script>window.location.href += \"/documentation/cordova\"</script>" > docs/index.html;

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'CordovaLib/docs'

      - id: deployment
        uses: actions/deploy-pages@v4
